" scratch area
:java (Vim/msg (Vim/buffer "2"))
:java (Vim/msg (.setAsCurrent (Vim/buffer "3")))
:java (Vim/msg (.getNumLines (Vim/buffer "2")))
:java (Vim/msg (.getLine (Vim/buffer "2") 1))
:java (Vim/msg (.setLine (Vim/buffer "2") 1 "foobar"))
:java (Vim/msg (.getName (Vim/buffer "2")))
:java (Vim/msg (.getFullName (Vim/buffer "2")))
:java (Vim/msg (.getNumber (Vim/buffer "2")))
:java (Vim/msg (.insertLine (Vim/buffer "2")  "\" last"))
:java (Vim/msg (.insertLine (Vim/buffer "2")  "\" first" 0))
:java (Vim/msg (.insertLine (Vim/buffer "2")  "\" middle" 5))
:java (Vim/msg (.next (Vim/buffer "2")))
:java (Vim/msg (.previous (Vim/buffer "2")))
:java (Vim/msg (.isValid (Vim/buffer "2")))
