:java (Vim/msg (import vim.Vim))
:java (Vim/msg (Vim/buffer "2"))
:java (Vim/msg (Vim/window "1"))
:java (Vim/msg (Vim/command "set cursorline"))
:java (Vim/msg (Vim/command "set nocursorline"))
:java (Vim/msg (Vim/line))
:java (Vim/msg (Vim/beep))
:java (Vim/msg (-> (Vim/open "window_test.vim") .setAsCurrent))
:java (Vim/msg (Vim/eval "&completeopt"))
:java (Vim/msg (-> (Vim/eval "&completeopt") .getClass .getName))
:java (Vim/msg (Vim/eval "&tw"))
:java (Vim/msg (-> (Vim/eval "&tw") .getClass .getName))
:java (Vim/msg (Vim/eval "3.14159"))
:java (Vim/msg (-> (Vim/eval "3.14159") .getClass .getName))
:java (Vim/emsg "error while erroring")

:java (Vim/command ":java (Vim/msg \"woah\")")
